name: Build and Serve React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # Specify the Node.js version you need

    - name: Install npm dependencies for the React app
      run: npm install

    - name: Build the Vite-based React app
      run: npm run build

    - name: Serve the React app
      run: npm run dev
